/**
 * Phase C — clinical-planning seeds: baseline, goals, barriers, the governed
 * template, the demonstration content library and plan v1.
 *
 * ALL content here is fictional demonstration content pending formal review by
 * Dr. Farhan, Dr. Meera and the discipline leads. It must never be presented
 * as validated treatment guidance.
 */
import type {
  DischargeSource,
  BarrierCategory,
  BaselineAssessment,
  ContentItem,
  FunctionalGoal,
  PatientPlan,
  ProtocolTemplate,
  RecoveryBarrier,
} from "./types";

export const DEMO_CONTENT_LABEL = "Demonstration content — not approved for clinical use.";

/* ---------------- Governed pathway/template (Layer 1) ---------------- */

export const protocolTemplate: ProtocolTemplate = {
  id: "tpl-stroke-home-1",
  name: "Stroke Home Continuity Pathway (demo)",
  version: "v0.2-demo",
  status: "approved",
  disciplineOwner: "pmr",
  evidenceSource: "Evidence references — placeholder pending clinical literature review",
  approvedBy: "Dr. Meera (PM&R Specialist)",
  approvedAt: "Before Day 0",
  reviewDue: "Day 90",
  intendedGroup: "Medically stable adults after stroke, discharged home in Bengaluru, with a reliable caregiver",
  inclusion: [
    "Medically stable adult stroke",
    "Reliable caregiver at home",
    "Smartphone and internet access",
    "Existing Lead Physiotherapist",
  ],
  exclusion: [
    "Medically unstable or current readmission → not eligible (exclusion rule)",
    "Known swallowing concern → clinical review before feeding-related content",
    "Seizure or respiratory concern → Clinical Operations review",
    "Continuous skilled-nursing requirement → clinical review",
  ],
  requiredBaselineDomains: [
    "Mobility & transfers",
    "Bed mobility & sitting",
    "Upper-limb function",
    "Pain / fatigue tolerance",
    "Cognition & communication",
    "Feeding / swallow status",
    "Caregiver capability",
    "Home environment & equipment",
  ],
  activityCategories: [
    "Positioning & pressure care",
    "Bed mobility & transfers",
    "Sitting balance",
    "Range of movement",
    "Caregiver education & handling",
    "ADL participation (via OT referral)",
    "Communication practice (via speech referral)",
  ],
  precautions: ["Falls risk during transfers", "Dysphagia — thickened feeds only until reviewed"],
  stopConditions: [
    "Sharp or more-than-mild pain",
    "Coughing or wet voice during feeding",
    "Dizziness, breathlessness or new weakness — stop and seek help",
  ],
  escalationRules: [
    "Red flags route to nursing triage (8 AM–8 PM IST)",
    "Medical concerns escalate to Dr. Farhan",
    "Emergencies: 112/108 first — Carelune is not an emergency service",
  ],
  indianAdaptationNotes: [
    "Instructions written for family caregivers, not clinic staff",
    "Floor-level living and shared bathrooms considered in home-environment checks",
    "Regional-language versions planned (Kannada first)",
  ],
  changeHistory: [
    { version: "v0.1-demo", date: "Pilot setup", by: "Ravi Kumar (draft)", note: "Initial demonstration draft" },
    { version: "v0.2-demo", date: "Before Day 0", by: "Dr. Meera", note: "Approved for demo use; added swallow-review trigger and Indian-adaptation notes" },
  ],
};

/* ---------------- Baseline (Lead Physiotherapist, Day 0) ---------------- */

export const baseline: BaselineAssessment = {
  assessedBy: "Ravi Kumar",
  assessorRole: "lead_physio",
  mode: "in_person",
  date: "Day 0",
  informationSources: "In-person assessment · discharge summary · caregiver interview",
  fields: [
    { id: "stroke", label: "Stroke date & type", value: "24 Apr 2026 · ischaemic, right MCA", source: "discharge_document" },
    { id: "side", label: "Affected side", value: "Left", source: "discharge_document" },
    { id: "home_status", label: "Discharge / home status", value: "Home since 27 Jun, spouse + hired caregiver", source: "clinician_assessed" },
    { id: "mobility", label: "Mobility & assistance level", value: "Wheelchair for distance; standing with one-person assist", source: "clinician_assessed" },
    { id: "bed_mobility", label: "Bed mobility", value: "Rolls with minimal help; needs setup for supine-to-sit", source: "clinician_assessed" },
    { id: "sitting", label: "Sitting ability", value: "Sits unsupported ~5 minutes on firm surface", source: "clinician_assessed" },
    { id: "transfer", label: "Transfer ability", value: "Bed-to-chair with one-person assist, occasionally unsteady", source: "clinician_assessed" },
    { id: "standing", label: "Standing / walking status", value: "Stands in parallel support; not yet walking independently", source: "clinician_assessed" },
    { id: "upper_limb", label: "Upper-limb functional status", value: "Left grasp weak; assists with dressing setup", source: "clinician_assessed" },
    { id: "pain", label: "Pain / movement-limiting concern", value: "Left-shoulder discomfort on end-range movement (≤2/10 reported)", source: "caregiver_reported" },
    { id: "fatigue", label: "Fatigue / tolerance", value: "Tires after ~20 minutes of activity; worse evenings", source: "caregiver_reported" },
    { id: "cognition", label: "Cognition / communication concern", value: "Word-finding difficulty noted; comprehension intact", source: "requires_other_discipline", discipline: "speech_swallow" },
    { id: "swallow", label: "Feeding / swallow concern", value: "On thickened feeds; needs formal swallow assessment", source: "requires_other_discipline", discipline: "speech_swallow" },
    { id: "caregiver", label: "Caregiver capability", value: "Lakshmi confident with meds; anxious about transfers", source: "caregiver_reported" },
    { id: "home_env", label: "Home environment constraints", value: "Ground floor; narrow bathroom door; grab-rail installed", source: "caregiver_reported" },
    { id: "equipment", label: "Equipment available", value: "Wheelchair; walker recommended, not yet acquired", source: "clinician_assessed" },
    { id: "precautions", label: "Precautions", value: "Falls risk; dysphagia precautions; HTN/T2DM under medical care", source: "discharge_document" },
    { id: "discharge_instr", label: "Existing discharge instructions", value: "Discharge summary on file; home-exercise sheet from inpatient rehab", source: "discharge_document" },
    { id: "mood", label: "Mood / participation", value: "Low mood post-stroke, on treatment — monitor participation", source: "not_assessed" },
  ],
};

/* ---------------- Functional goals (above interventions & tasks) ---------------- */

export const goals: FunctionalGoal[] = [
  {
    id: "g1",
    patientWording: "Move to my chair without feeling I might fall",
    clinicalFormulation: "Safer assisted bed-to-chair transfer with one-person assist",
    domain: "Mobility & transfers",
    ownerRole: "lead_physio",
    baseline: "One-person assist, occasionally unsteady (baseline Day 0)",
    target: "Consistent, steady one-person-assist transfer with correct setup",
    timeframe: "By Day 30",
    priority: "high",
    status: "progressing",
    barrierIds: ["b1", "b3"],
    facilitators: ["Motivated patient", "Grab-rail installed", "Caregiver present at all transfers"],
    interventionIds: ["iv1", "iv2"],
    reviewDate: "Day 14 (weekly review)",
    evidenceSource: "Clinician observation at baseline; caregiver report",
  },
  {
    id: "g2",
    patientWording: "Sit up on my own to eat and talk with family",
    clinicalFormulation: "Maintain supported sitting for a defined period (target 15 minutes)",
    domain: "Sitting balance",
    ownerRole: "lead_physio",
    baseline: "Sits unsupported ~5 minutes on firm surface",
    target: "15 minutes supported sitting during meals and visits",
    timeframe: "By Day 21",
    priority: "high",
    status: "progressing",
    barrierIds: ["b1"],
    facilitators: ["Firm chair with armrests available"],
    interventionIds: ["iv3"],
    reviewDate: "Day 14 (weekly review)",
    evidenceSource: "Clinician observation at baseline",
  },
  {
    id: "g3",
    patientWording: "Wash my own face in the morning",
    clinicalFormulation: "Improve participation in morning self-care (setup-level assistance)",
    domain: "ADLs & self-care",
    ownerRole: "occupational_therapist",
    baseline: "Assists with setup only; caregiver completes most steps",
    target: "Completes face-washing and grooming with setup assistance",
    timeframe: "By Day 30",
    priority: "medium",
    status: "not_started",
    barrierIds: ["b2"],
    facilitators: ["Right hand fully functional"],
    interventionIds: [],
    reviewDate: "After OT review",
    evidenceSource: "Caregiver report",
    revisionRationale: "Held at goal level — detailed self-care interventions await the OT referral outcome.",
  },
  {
    id: "g4",
    patientWording: "Eat meals without the coughing scare",
    clinicalFormulation: "Safe feeding review — pending appropriate swallow assessment",
    domain: "Swallow & feeding safety",
    ownerRole: "speech_swallow",
    baseline: "Thickened feeds; one wet-voice episode reported (Tuesday lunch)",
    target: "Feeding plan confirmed by swallow assessment",
    timeframe: "Assessment this week",
    priority: "high",
    status: "held",
    barrierIds: ["b2"],
    facilitators: ["Caregiver trained in supported-feeding education"],
    interventionIds: ["iv4"],
    reviewDate: "On specialist review",
    evidenceSource: "Caregiver report; nursing triage note",
    revisionRationale: "Held pending speech-and-swallow assessment — no feeding change without the owning discipline.",
  },
  {
    id: "g5",
    patientWording: "Lakshmi wants to feel sure she's doing it right",
    clinicalFormulation: "Improve caregiver confidence with positioning and transfer setup",
    domain: "Caregiver capability",
    ownerRole: "nurse",
    baseline: "Anxious about transfers; confident with medication record",
    target: "Independently sets up safe transfers and 2-hourly positioning",
    timeframe: "By Day 21",
    priority: "medium",
    status: "progressing",
    barrierIds: ["b3"],
    facilitators: ["Completed onboarding training", "Asks questions readily"],
    interventionIds: ["iv5"],
    reviewDate: "Day 14",
    evidenceSource: "Caregiver self-report at onboarding",
  },
];

/* ---------------- Recovery barriers (structured, never scored) ---------------- */

export const BARRIER_CATEGORY_LABEL: Record<BarrierCategory, string> = {
  medical_stability: "Medical stability",
  pain: "Pain",
  fatigue: "Fatigue",
  cognition: "Cognition",
  communication: "Communication",
  swallow_feeding: "Swallow / feeding",
  mood_motivation: "Mood / motivation",
  caregiver_confidence: "Caregiver confidence",
  caregiver_availability: "Caregiver availability",
  home_accessibility: "Home accessibility",
  equipment: "Equipment",
  financial: "Financial",
  transport: "Transport",
  digital_access: "Digital access",
  nutrition: "Nutrition",
  family_coordination: "Family coordination",
  other: "Other",
};

export const barriers: RecoveryBarrier[] = [
  {
    id: "b1",
    category: "fatigue",
    label: "Tires after ~20 minutes; evening sessions poorly tolerated",
    source: "Lakshmi (caregiver report)",
    severity: "moderate",
    ownerRole: "lead_physio",
    actionRequired: "Schedule demanding tasks in the morning; review dosage at weekly review",
    linkedGoalIds: ["g1", "g2"],
    status: "in_progress",
    reviewDate: "Day 14",
  },
  {
    id: "b2",
    category: "swallow_feeding",
    label: "Dysphagia on thickened feeds; wet-voice episode Tuesday",
    source: "Lakshmi (caregiver report) · nursing triage",
    severity: "significant",
    ownerRole: "speech_swallow",
    actionRequired: "Specialist swallow assessment before any feeding change",
    linkedGoalIds: ["g4", "g3"],
    status: "open",
    reviewDate: "On specialist review",
  },
  {
    id: "b3",
    category: "caregiver_confidence",
    label: "Caregiver anxious about transfer setup",
    source: "Divya (onboarding record)",
    severity: "moderate",
    ownerRole: "nurse",
    actionRequired: "Positioning & handling education sessions; observe a transfer on video review",
    linkedGoalIds: ["g1", "g5"],
    status: "in_progress",
    reviewDate: "Day 14",
  },
  {
    id: "b4",
    category: "equipment",
    label: "Walker recommended but not yet acquired",
    source: "Ravi Kumar (baseline)",
    severity: "mild",
    ownerRole: "coordinator",
    actionRequired: "Family to arrange walker with their own supplier; coordinator follows up",
    linkedGoalIds: ["g1"],
    status: "resolved",
    reviewDate: "Day 10",
    resolutionNote: "Family purchased a walker on Day 9 (their own supplier — Carelune sells no equipment).",
  },
];

/* ---------------- Demonstration content library (6–10 items) ---------------- */

export const contentLibrary: ContentItem[] = [
  {
    id: "c1",
    discipline: "lead_physio",
    domain: "Mobility & transfers",
    title: "Assisted bed-to-chair transfer practice",
    intendedCapability: "Sits on bed edge with supervision; bears weight briefly",
    startingPosition: "Sitting on bed edge, feet flat, chair angled at 45°",
    performedBy: "Patient with one caregiver assisting",
    instructions: "Set the chair close on the stronger side; block the weak knee; stand on count of three; pivot slowly.",
    doseFields: ["repetitions", "times per day", "assistance level"],
    assistance: "One-person assist",
    equipment: ["Stable chair with armrests"],
    contraindications: ["Uncontrolled dizziness", "New chest pain"],
    precautions: ["Falls risk — clear the floor; non-slip footwear"],
    stopConditions: ["Sharp pain", "More than mild breathlessness", "Increasing unsteadiness"],
    deliveryModesAllowed: ["caregiver_guided", "recorded_review", "home_visit"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Ravi Kumar",
    reviewer: "Dr. Meera (PM&R)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: true,
  },
  {
    id: "c2",
    discipline: "lead_physio",
    domain: "Sitting balance",
    title: "Supported sitting-balance practice",
    intendedCapability: "Sits unsupported ≥3 minutes on a firm surface",
    startingPosition: "Sitting on firm chair, feet flat, table in front",
    performedBy: "Patient; caregiver within arm's reach",
    instructions: "Sit tall; small reaches to the table edge; rest between sets.",
    doseFields: ["minutes per session", "sessions per day"],
    assistance: "Supervision (contact guard)",
    equipment: ["Firm chair", "Table"],
    contraindications: ["Unhealed pressure area over sitting surface"],
    precautions: ["Guard on the weak side"],
    stopConditions: ["Leaning that doesn't self-correct", "Dizziness"],
    deliveryModesAllowed: ["caregiver_guided", "recorded_review", "live_virtual"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Ravi Kumar",
    reviewer: "Dr. Meera (PM&R)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: false,
  },
  {
    id: "c3",
    discipline: "lead_physio",
    domain: "Range of movement",
    title: "Assisted shoulder range-of-movement set",
    intendedCapability: "Tolerates passive movement without sharp pain",
    startingPosition: "Lying or supported sitting",
    performedBy: "Caregiver moving the limb, patient assisting where able",
    instructions: "Slow, smooth movements to comfortable range; never push through pain.",
    doseFields: ["repetitions per joint", "sets per day"],
    assistance: "Caregiver performs with patient participation",
    equipment: [],
    contraindications: ["Recent shoulder injury"],
    precautions: ["Subluxation care — support the arm's weight"],
    stopConditions: ["Sharp or more-than-mild pain"],
    deliveryModesAllowed: ["caregiver_guided", "recorded_review"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Ravi Kumar",
    reviewer: "Dr. Meera (PM&R)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: false,
  },
  {
    id: "c10",
    discipline: "lead_physio",
    domain: "Mobility & transfers",
    title: "Supported standing-tolerance practice",
    intendedCapability: "Achieves standing with one-person assist; no orthostatic symptoms",
    startingPosition: "Standing at a stable surface (kitchen counter or heavy table)",
    performedBy: "Patient with one caregiver guarding",
    instructions: "Stand tall holding the surface; shift weight gently side to side; sit down before tiring.",
    doseFields: ["standing time per bout", "bouts per day"],
    assistance: "One-person guard",
    equipment: ["Stable counter or heavy table", "Chair behind the patient"],
    contraindications: ["Dizziness on standing"],
    precautions: ["Chair always directly behind", "Never leave unattended in standing"],
    stopConditions: ["Dizziness, breathlessness or knee giving way — sit immediately"],
    deliveryModesAllowed: ["caregiver_guided", "recorded_review", "home_visit"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Ravi Kumar",
    reviewer: "Dr. Meera (PM&R)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: true,
  },
  {
    id: "c4",
    discipline: "occupational_therapist",
    domain: "ADLs & self-care",
    title: "Morning grooming participation (setup method)",
    intendedCapability: "Supported sitting; functional grip in one hand",
    startingPosition: "Seated at basin or with a bowl at a stable table",
    performedBy: "Patient with caregiver setup",
    instructions: "Caregiver sets out items in reach order; patient completes face-washing steps at own pace.",
    doseFields: ["steps attempted", "assistance level"],
    assistance: "Setup assistance",
    equipment: ["Stable seat", "Basin or bowl"],
    contraindications: [],
    precautions: ["Water spill / slip risk"],
    stopConditions: ["Fatigue affecting sitting safety"],
    deliveryModesAllowed: ["caregiver_guided", "recorded_review", "home_visit"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.1-demo",
    language: "English",
    author: "OT panel (fictional)",
    reviewer: "Dr. Meera (PM&R)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: false,
  },
  {
    id: "c5",
    discipline: "occupational_therapist",
    domain: "Upper-limb function",
    title: "Graded grasp-and-release practice",
    intendedCapability: "Initiates grasp with the affected hand",
    startingPosition: "Supported sitting at a table",
    performedBy: "Patient; caregiver arranges objects",
    instructions: "Grasp, hold, place — large light objects first; rest between sets.",
    doseFields: ["objects per set", "sets per day"],
    assistance: "Setup and encouragement",
    equipment: ["Household objects of varied size"],
    contraindications: [],
    precautions: ["Watch for frustration; keep sessions short"],
    stopConditions: ["Pain in hand or shoulder"],
    deliveryModesAllowed: ["caregiver_guided", "recorded_review"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.1-demo",
    language: "English",
    author: "OT panel (fictional)",
    reviewer: "Dr. Meera (PM&R)",
    approval: "draft",
    reviewDue: "Pending review",
    observationRequired: false,
  },
  {
    id: "c6",
    discipline: "speech_swallow",
    domain: "Communication",
    title: "Picture-naming conversation practice",
    intendedCapability: "Comprehension intact; word-finding difficulty",
    startingPosition: "Seated, rested, quiet room",
    performedBy: "Patient with caregiver showing cards",
    instructions: "Show a card; give time; encourage any response; never correct sharply.",
    doseFields: ["cards per session", "sessions per day"],
    assistance: "Caregiver facilitates",
    equipment: ["Picture cards"],
    contraindications: [],
    precautions: ["Stop if frustration rises — this is practice, not testing"],
    stopConditions: ["Distress or refusal"],
    deliveryModesAllowed: ["caregiver_guided", "live_virtual", "recorded_review"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Speech panel (fictional)",
    reviewer: "Dr. Meera (PM&R)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: false,
  },
  {
    id: "c7",
    discipline: "speech_swallow",
    domain: "Swallow & feeding safety",
    title: "Safe supported feeding — caregiver education (thickened feeds)",
    intendedCapability: "Alert, on thickened feeds per discharge plan",
    startingPosition: "Sitting fully upright at 90°",
    performedBy: "Caregiver feeding; patient participating",
    instructions: "Upright at 90°; small spoons; chin slightly down; pause between spoons; stop on any cough.",
    doseFields: ["texture per current plan", "supervision level"],
    assistance: "Full caregiver supervision",
    equipment: ["Thickener as prescribed"],
    contraindications: ["Reduced alertness", "Active chest infection"],
    precautions: ["Aspiration risk — education only; changes need the swallow specialist"],
    stopConditions: ["Coughing or wet-sounding voice — stop and request help"],
    deliveryModesAllowed: ["caregiver_guided", "home_visit"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Speech panel (fictional)",
    reviewer: "Dr. Farhan (Medical Clinician)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: true,
  },
  {
    id: "c8",
    discipline: "nurse",
    domain: "Caregiver handling & positioning",
    title: "Two-hourly positioning & pressure-care routine",
    intendedCapability: "Any — caregiver-performed",
    startingPosition: "Patient in bed or chair",
    performedBy: "Caregiver",
    instructions: "Turn every 2 hours; pillow between knees; check heels and sacrum for redness.",
    doseFields: ["turn frequency", "skin-check points"],
    assistance: "Caregiver performs",
    equipment: ["Pillows"],
    contraindications: [],
    precautions: ["Report any persistent redness the same day"],
    stopConditions: ["New skin break — stop and call the nurse line"],
    deliveryModesAllowed: ["caregiver_guided", "home_visit"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Nisha (Rehabilitation Nurse)",
    reviewer: "Dr. Farhan (Medical Clinician)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: false,
  },
  {
    id: "c9",
    discipline: "nurse",
    domain: "Caregiver handling & positioning",
    title: "Safe transfer setup — caregiver education",
    intendedCapability: "Any — caregiver-performed",
    startingPosition: "Before each transfer",
    performedBy: "Caregiver",
    instructions: "Clear the path; lock the wheelchair; correct chair angle; agree the count with the patient.",
    doseFields: ["checklist use per transfer"],
    assistance: "Caregiver performs",
    equipment: ["Wheelchair with working brakes"],
    contraindications: [],
    precautions: ["Never rush a transfer"],
    stopConditions: ["Patient dizzy or unwilling — postpone and report"],
    deliveryModesAllowed: ["caregiver_guided", "home_visit", "live_virtual"],
    evidenceSource: "Evidence placeholder — pending review",
    version: "v0.2-demo",
    language: "English",
    author: "Nisha (Rehabilitation Nurse)",
    reviewer: "Dr. Farhan (Medical Clinician)",
    approval: "approved",
    reviewDue: "Day 90",
    observationRequired: false,
  },
];


/* ---------------- Verified discharge source (Anand) ---------------- */

/**
 * The only discharge document Carelune has transcribed and verified. Anything
 * claiming "continued from discharge plan" must reference a record like this,
 * complete, or it cannot reach the caregiver.
 */
export const dischargeSource: DischargeSource = {
  document: "Inpatient rehabilitation discharge summary + feeding advice sheet",
  institution: "Inpatient rehabilitation centre, Bengaluru (fictional)",
  issuingProfessional: "Dr. A. Rao, Rehabilitation Physician (fictional)",
  documentDate: "27 Jun 2026",
  verificationStatus: "verified",
  transcribedBy: "Divya (Recovery Care Coordinator)",
  confirmedCurrentBy: "Dr. Farhan (Medical Clinician & Clinical Operations Lead)",
  confirmedCurrentAt: "Day 0",
};

/* ---------------- Plan v1 (Layer 2) — the active approved plan ---------------- */

export const seedPlan: PatientPlan = {
  version: 1,
  status: "active",
  templateId: protocolTemplate.id,
  templateVersion: protocolTemplate.version,
  approvedBy: "Ravi Kumar (Lead Physiotherapist)",
  approvedAt: "Day 1",
  interventions: [
    {
      id: "iv1",
      goalId: "g1",
      contentId: "c1",
      title: "Assisted bed-to-chair transfer practice",
      caregiverTitle: "Practise moving to the chair",
      kind: "clinical",
      ownerRole: "lead_physio",
      deliveryMode: "caregiver_guided",
      dose: "3 repetitions",
      frequency: "Twice daily",
      assistance: "One-person assist",
      equipment: ["Stable chair with armrests"],
      instructions:
        "Set the chair close on his stronger side. Block his weak knee with yours. Stand together on the count of three, then turn slowly and sit.",
      whyItMatters: "Steadier transfers are the first step towards standing safely.",
      precautions: ["Falls risk — clear the floor; non-slip footwear"],
      safetyInstructions: [
        "Stop at once if he has sharp pain, feels dizzy, or becomes more unsteady.",
      ],
      scheduleSegment: "Morning",
      scheduleTime: "08:30",
      timeWindow: "Morning · around 08:30",
      priority: "recovery_priority",
      priorityReason: "Main goal this month — steady one-person transfers.",
      rationale: "Baseline shows unsteady one-person transfers; goal g1 is high priority.",
      status: "active",
      addedInVersion: 1,
      provenance: {
        sourceKind: "carelune_content",
        sourceVersion: "Content c1 v0.2-demo · Pathway v0.2-demo",
        approvedBy: "Ravi Kumar",
        approverRole: "lead_physio",
        approvedAt: "Day 1",
        reviewDate: "Day 14",
      },
    },
    {
      id: "iv2",
      goalId: "g1",
      contentId: "c3",
      title: "Assisted shoulder range-of-movement set",
      caregiverTitle: "Gentle arm movements",
      kind: "clinical",
      ownerRole: "lead_physio",
      deliveryMode: "caregiver_guided",
      dose: "10 slow repetitions each joint",
      frequency: "Once daily",
      assistance: "You move the arm; he helps where he can",
      equipment: [],
      instructions:
        "Support the weight of his arm. Move slowly and smoothly, only as far as is comfortable.",
      whyItMatters: "Keeps the shoulder loose and comfortable while he builds strength.",
      precautions: ["Support the arm's weight (subluxation care)"],
      safetyInstructions: ["Never push through pain — stop if it is more than mild."],
      scheduleSegment: "Morning",
      scheduleTime: "09:00",
      timeWindow: "Morning · around 09:00",
      priority: "routine_support",
      priorityReason: "Supports the transfer goal; flexible timing.",
      rationale: "Maintain range while transfer work progresses.",
      status: "active",
      addedInVersion: 1,
      provenance: {
        sourceKind: "carelune_content",
        sourceVersion: "Content c3 v0.2-demo · Pathway v0.2-demo",
        approvedBy: "Ravi Kumar",
        approverRole: "lead_physio",
        approvedAt: "Day 1",
        reviewDate: "Day 14",
      },
    },
    {
      id: "iv3",
      goalId: "g2",
      contentId: "c2",
      title: "Supported sitting-balance practice",
      caregiverTitle: "Sitting practice",
      kind: "clinical",
      ownerRole: "lead_physio",
      deliveryMode: "caregiver_guided",
      dose: "Up to 10 minutes",
      frequency: "Once daily",
      assistance: "Stay within arm's reach",
      equipment: ["Firm chair", "Table"],
      instructions:
        "Sit him tall in the firm chair with feet flat. Ask for small reaches to the table edge. Rest between tries.",
      whyItMatters: "Sitting steadily lets him eat and talk with the family more comfortably.",
      precautions: ["Guard the weak side"],
      safetyInstructions: ["Stop if he leans and cannot correct it, or feels dizzy."],
      scheduleSegment: "Midday",
      scheduleTime: "15:30",
      timeWindow: "Afternoon · around 15:30",
      priority: "recovery_priority",
      priorityReason: "Builds towards sitting through a whole meal.",
      rationale: "Builds toward 15-minute meal-time sitting (goal g2).",
      status: "active",
      addedInVersion: 1,
      provenance: {
        sourceKind: "carelune_content",
        sourceVersion: "Content c2 v0.2-demo · Pathway v0.2-demo",
        approvedBy: "Ravi Kumar",
        approverRole: "lead_physio",
        approvedAt: "Day 1",
        reviewDate: "Day 14",
      },
    },
    {
      /* Correction 3 — therapeutic positioning sits in physiotherapy scope. */
      id: "iv6",
      goalId: "g1",
      contentId: undefined,
      title: "Supported arm positioning at rest (therapeutic positioning)",
      caregiverTitle: "Position his weak arm when resting",
      kind: "clinical",
      ownerRole: "lead_physio",
      deliveryMode: "caregiver_guided",
      dose: "At each rest period",
      frequency: "Through the day",
      assistance: "You position; he stays relaxed",
      equipment: ["Pillow"],
      instructions:
        "When he rests, place the weak arm forward on a pillow, palm down, shoulder supported — not hanging over the edge.",
      whyItMatters: "Protects the weak shoulder while he is not moving.",
      precautions: ["Do not let the arm hang unsupported"],
      safetyInstructions: ["Stop and tell us if the shoulder looks swollen or he complains of pain at rest."],
      scheduleSegment: "Evening",
      scheduleTime: "19:00",
      timeWindow: "Evening · around 19:00",
      priority: "routine_support",
      priorityReason: "Protects the shoulder between activity sessions.",
      rationale:
        "Therapeutic positioning of the hemiplegic limb — physiotherapy scope, approved by the Lead Physiotherapist.",
      status: "active",
      addedInVersion: 1,
      provenance: {
        sourceKind: "carelune_content",
        sourceVersion: "Pathway v0.2-demo · activity category: Positioning & pressure care",
        approvedBy: "Ravi Kumar",
        approverRole: "lead_physio",
        approvedAt: "Day 1",
        reviewDate: "Day 14",
      },
    },
    {
      /* Correction 3 — nursing education (skin protection & observation) stays with nursing. */
      id: "iv5",
      goalId: "g5",
      contentId: "c8",
      title: "Pressure-area care & skin observation (nursing education)",
      caregiverTitle: "Turn him and check his skin",
      kind: "education",
      ownerRole: "nurse",
      deliveryMode: "caregiver_guided",
      dose: "Turn every 2 hours; check heels and lower back",
      frequency: "Through the day",
      assistance: "You do this",
      equipment: ["Pillows"],
      instructions:
        "Change his position every two hours. Put a pillow between the knees. Look at the heels and lower back for redness that does not fade.",
      whyItMatters: "Protects the skin during the hours he spends sitting or lying.",
      precautions: ["Report redness that does not fade the same day"],
      safetyInstructions: ["If the skin is broken or blistered, stop and call the nurse line."],
      scheduleSegment: "Midday",
      scheduleTime: "14:00",
      timeWindow: "Afternoon · around 14:00",
      priority: "safety_critical",
      priorityReason: "Skin protection — missing turns risks a pressure injury.",
      rationale:
        "Nursing education: skin protection, comfort and observation. Not therapeutic positioning.",
      status: "active",
      addedInVersion: 1,
      provenance: {
        sourceKind: "carelune_content",
        sourceVersion: "Content c8 v0.2-demo",
        approvedBy: "Nisha (Rehabilitation Nurse)",
        approverRole: "nurse",
        approvedAt: "Day 1",
        reviewDate: "Day 14",
      },
    },
    {
      /* Correction 2 — feeding is HELD; the verified discharge precaution is shown, not a plan. */
      id: "iv4",
      goalId: "g4",
      contentId: "c7",
      title: "Feeding & swallowing plan",
      caregiverTitle: "Mealtime safety",
      kind: "clinical",
      ownerRole: "speech_swallow",
      deliveryMode: "hold_reassessment",
      dose: "Not set — awaiting specialist",
      frequency: "Not set — awaiting specialist",
      assistance: "Full supervision at every meal",
      equipment: ["Thickener as prescribed at discharge"],
      instructions:
        "Continue exactly as the discharge sheet says. Nothing here has been changed by Carelune.",
      whyItMatters: "Swallowing safety belongs to the speech and swallow specialist.",
      precautions: ["Aspiration risk"],
      safetyInstructions: [
        "Stop feeding and request help if he coughs or his voice sounds wet.",
      ],
      scheduleSegment: "Morning",
      scheduleTime: "07:30",
      timeWindow: "Each meal",
      priority: "safety_critical",
      priorityReason: "Swallowing safety — specialist review pending.",
      rationale:
        "No Carelune swallow-treatment plan exists. Only the verified discharge precaution is displayed while the speech-and-swallow referral is open.",
      status: "held",
      holdReason:
        "Held pending Speech & Swallow Therapist reassessment — no Carelune feeding plan is active.",
      precautionDisplay:
        "Verified discharge precaution — awaiting specialist reassessment: sit fully upright at 90°, thickened feeds as prescribed at discharge, small spoons, stop at any cough or wet voice.",
      addedInVersion: 1,
      provenance: {
        sourceKind: "discharge_plan",
        sourceVersion: "Discharge summary 27 Jun 2026 · feeding advice sheet",
        approvedBy: "Awaiting Speech & Swallow Therapist",
        approverRole: "speech_swallow",
        approvedAt: "—",
        reviewDate: "On specialist review",
        discharge: dischargeSource,
      },
    },
    {
      /* Communication practice — speech-owned, no approval chain, therefore held. */
      id: "iv7",
      goalId: "g4",
      contentId: "c6",
      title: "Picture-naming communication practice",
      caregiverTitle: "Word practice with cards",
      kind: "clinical",
      ownerRole: "speech_swallow",
      deliveryMode: "hold_reassessment",
      dose: "Not set — awaiting specialist",
      frequency: "Not set — awaiting specialist",
      assistance: "You show the cards",
      equipment: ["Picture cards"],
      instructions: "Awaiting the speech and swallow specialist's own instructions.",
      whyItMatters: "Word-finding practice belongs to the speech specialist.",
      precautions: [],
      safetyInstructions: ["Stop if he becomes distressed."],
      scheduleSegment: "Midday",
      scheduleTime: "11:00",
      timeWindow: "Late morning",
      priority: "routine_support",
      priorityReason: "Held — awaiting the owning discipline.",
      rationale:
        "Approved content exists, but assignment and parameters must come from the Speech & Swallow Therapist.",
      status: "held",
      holdReason: "Held pending Speech & Swallow Therapist review — referral open.",
      addedInVersion: 1,
      provenance: {
        sourceKind: "carelune_content",
        sourceVersion: "Content c6 v0.2-demo",
        approvedBy: "Awaiting Speech & Swallow Therapist",
        approverRole: "speech_swallow",
        approvedAt: "—",
        reviewDate: "On specialist review",
      },
    },
  ],
  history: [
    {
      version: 1,
      at: "Day 1",
      by: "Ravi Kumar",
      change: "Plan v1 activated from Stroke Home Continuity Pathway v0.2-demo",
      rationale:
        "Baseline complete; goals g1–g5 set; caregiver trained. Feeding and communication held pending Speech & Swallow review; pressure-area care approved by Nisha as nursing education.",
    },
  ],
};

/**
 * Static lookup for screens that read the seeded plan directly (the live store
 * exposes its own `interventionTitle` covering interventions added in-session).
 * Internal ids must never be rendered.
 */
export const seedInterventionTitle = (id: string) =>
  seedPlan.interventions.find((i) => i.id === id)?.title ?? "Intervention";
